const captchagen = require('captchagen');
function createCaptcha(){
    let captcha = captchagen.create();
    let text = captcha.text();     // Returns captcha text (randomly generated by default)
    let height = captcha.height();   // Returns captcha height (150 by default)
    let width = captcha.width();    // Returns captcha width (300 by default)
    captcha.generate(); // Draws the image to the canvas
    return new Promise( (y,n)=>{
        captcha.buffer((err, buffer)=>{
            if(err){
                n(err);
                return;
            }
            
            y({
                text,
                height,
                width,
                buffer
            });
        });
    });
}
    
module.exports = {createCaptcha};