const CURRENCY = {
"AED":["阿聯酋迪拉姆","United Arab Emirates Dirham"],
"AFN":["阿富汗尼","Afghan Afghani"],
"ALL":["阿爾巴尼列克","Albania Lek"],
"AMD":["亞美尼亞德拉姆","Armenia Dram"],
"ANG":["荷蘭盾","Antilles Guilder"],
"AOA":["安哥拉寬扎","Angola Kwanza"],
"ARS":["阿根廷比索","Argentina Peso"],
"AUD":["澳元","Australia Dollar"],
"AWG":["阿魯巴弗羅林","Aruba Florin"],
"AZN":["阿塞拜疆馬納特","Azerbaijan Manat"],
"BAM":["波黑可兌換馬克","Bosnia Convertible Mark"],
"BBD":["巴巴多斯元","Barbados Dollar"],
"BDT":["孟加拉國塔卡","Bangladesh Taka"],
"BGN":["保加利亞列弗","Bulgaria Lev"],
"BHD":["巴林第納爾","Bahrain Dinar"],
"BIF":["布隆迪法郎","Burundi Franc"],
"BMD":["百慕大元","Bermudian Dollar"],
"BND":["文萊元","Brunei Dollar"],
"BOB":["玻利維亞諾","Boliviano"],
"BRL":["巴西雷亞爾","Brazilian Real"],
"BSD":["巴哈馬元","Bahamian Dollar"],
"BTN":["不丹努扎姆","Bhutanese Ngultrum"],
"BWP":["博茨瓦納普拉","Botswana Pula "],
"BYR":["白俄羅斯盧布","Belarusian Ruble"],
"BZD":["伯利茲元","Belize Dollar"],
"CAD":["加元","Canadian Dollar"],
"CDF":["剛果法郎","Franc Congolais"],
"CHF":["瑞士法郎","Swiss Franc"],
"CLF":["智利比索(基金)","Chilean Unidad de Fomento"],
"CLP":["智利比索","Chilean Peso"],
"CNH":["中國離岸人民幣","Chinese Offshore Renminbi"],
"CNY":["人民幣","Chinese Yuan"],
"COP":["哥倫比亞比索","Colombia Peso "],
"CRC":["哥斯達黎加科朗","Costa Rica Colon"],
"CUP":["古巴比索","Cuban Peso"],
"CVE":["佛得角埃斯庫多","Cape Verde Escudo"],
"CYP":["塞普路斯鎊","Cyprus Pound"],
"CZK":["捷剋剋朗","Czech Republic Koruna"],
"DEM":["德國馬克","German Mark"],
"DJF":["吉布提法郎","Djiboutian Franc"],
"DKK":["丹麥克郎","Danish Krone"],
"DOP":["多米尼加比索","Dominican Peso"],
"DZD":["阿爾及利亞第納爾","Algerian Dinar "],
"ECS":["厄瓜多爾蘇克雷","Ecuadorian Sucre"],
"EGP":["埃及鎊","Egyptian Pound"],
"ERN":["厄立特里亞納克法","Eritrean Nakfa"],
"ETB":["埃塞俄比亞比爾","Ethiopian Birr"],
"EUR":["歐元","Euro"],
"FJD":["斐濟元","Fiji Dollar"],
"FKP":["福克蘭群島鎊","Falkland Islands Pound"],
"FRF":["法國法郎","French Franc"],
"GBP":["英鎊","Pound Sterling"],
"GEL":["格魯吉亞拉里","Georgian Lari"],
"GHS":["加納塞地","Ghanaian Cedi"],
"GIP":["直布羅陀鎊","Gibraltar Pound"],
"GMD":["岡比亞達拉西","Gambian Dalasi"],
"GNF":["幾內亞法郎","Guinean Franc"],
"GTQ":["危地馬拉格查爾","Guatemalan Quetzal"],
"GYD":["圭亞那元","Guyanese Dollar"],
"HKD":["港幣","Hong Kong Dollar"],
"HNL":["洪都拉斯倫皮拉","Honduran Lempira"],
"HRK":["克羅地亞庫納","Croatian Kuna"],
"HTG":["海地古德","Haitian Gourde"],
"HUF":["匈牙利福林","Hungarian Forint"],
"IDR":["印度尼西亞盧比","Indonesian Rupiah"],
"IEP":["愛爾蘭鎊","Irish Pound"],
"ILS":["以色列新謝克爾","Israeli New Shekel"],
"INR":["印度盧比","Indian Rupee"],
"IQD":["伊拉克第納爾","Iraqi Dinar"],
"IRR":["伊朗里亞爾","Iranian Rial"],
"ISK":["冰島克郎","Icelandic Krona"],
"ITL":["意大利里拉","Italian Lira"],
"JMD":["牙買加元","Jamaican Dollar"],
"JOD":["約旦第納爾","Jordanian Dinar"],
"JPY":["日元","Japanese Yen"],
"KES":["肯尼亞先令","Kenyan Shilling"],
"KGS":["吉爾吉斯斯坦索姆","Kyrgyzstani Som"],
"KHR":["柬埔寨瑞爾","Cambodian Riel"],
"KMF":["科摩羅法郎","Comorian franc"],
"KPW":["朝鮮元","North Korean Won"],
"KRW":["韓元","South Korean Won"],
"KWD":["科威特第納爾","Kuwaiti Dinar"],
"KYD":["開曼群島元","Cayman Islands Dollar"],
"KZT":["哈薩克斯坦騰格","Kazakstani Tenge"],
"LAK":["老撾基普","Lao kip"],
"LBP":["黎巴嫩鎊","Lebanese Pound"],
"LKR":["斯里蘭卡盧比","Sri Lankan Rupee"],
"LRD":["利比里亞元","Liberian dollar"],
"LSL":["萊索托洛蒂","Lesotho Loti"],
"LTL":["立陶宛立特","Lithuanian Litas"],
"LVL":["拉脫維亞拉特","Latvian Lats"],
"LYD":["利比亞第納爾","Libyan Dinar"],
"MAD":["摩洛哥迪拉姆","Moroccan Dirham"],
"MDL":["摩爾多瓦列伊","Moldovan Leu"],
"MGA":["馬達加斯加阿里亞里","Malagasy Ariary"],
"MKD":["馬其頓代納爾","Macedonian Denar"],
"MMK":["緬甸元","Myanmar Kyat"],
"MNT":["蒙古圖格里克","Mongolian Tugrik"],
"MOP":["澳門元","Macau Pataca"],
"MRO":["毛裡塔尼亞烏吉亞","Mauritania Ouguiya"],
"MUR":["毛里求斯盧比","Mauritian Rupee"],
"MVR":["馬爾代夫拉菲亞","Maldives Rufiyaa"],
"MWK":["馬拉維克瓦查","Malawian Kwacha"],
"MXN":["墨西哥比索","Mexican Peso"],
"MXV":["墨西哥MXV","Mexican Unidad De Inversion"],
"MYR":["馬來西亞林吉特","Malaysian Ringgit"],
"MZN":["莫桑比克新梅蒂卡爾","New Mozambican Metical"],
"NAD":["納米比亞元","Namibian Dollar"],
"NGN":["尼日利亞奈拉","Nigerian Naira"],
"NIO":["尼加拉瓜新科多巴","Nicaraguan Cordoba Oro"],
"NOK":["挪威克朗","Norwegian Krone"],
"NPR":["尼泊爾盧比","Nepalese Rupee"],
"NZD":["新西蘭元","New Zealand Dollar"],
"OMR":["阿曼里亞爾","Omani Rial"],
"PAB":["巴拿馬巴波亞","Panamanian Balboa"],
"PEN":["秘魯新索爾","Peruvian Nuevo Sol"],
"PGK":["巴布亞新幾內亞基那","Papua New Guinea Kina"],
"PHP":["菲律賓比索","Philippine Peso"],
"PKR":["巴基斯坦盧比","Pakistan Rupee"],
"PLN":["波蘭茲羅提","Polish Zloty"],
"PYG":["巴拉圭瓜拉尼","Paraguayan Guarani"],
"QAR":["卡塔爾里亞爾","Qatari Riyal"],
"RON":["羅馬尼亞列伊","Romanian Leu"],
"RSD":["塞爾維亞第納爾","Serbian Dinar"],
"RUB":["俄羅斯盧布","Russian Ruble"],
"RWF":["盧旺達法郎","Rwandan Franc"],
"SAR":["沙特里亞爾","Saudi Arabian Riyal"],
"SBD":["所羅門群島元","Solomon Islands Dollar"],
"SCR":["塞舌爾盧比","Seychelles Rupee"],
"SDG":["蘇丹磅","Sudanese Pound"],
"SEK":["瑞典克朗","Swedish Krona"],
"SGD":["新加坡元","Singapore Dollar"],
"SHP":["聖赫勒拿鎊","Saint Helena Pound"],
"SIT":["斯洛文尼亞托拉爾","Slovenian Tolar"],
"SLL":["塞拉利昂利昂","Sierra Leonean Leone"],
"SOS":["索馬里先令","Somali Shilling"],
"SRD":["蘇里南元","Suriname Dollar"],
"STD":["聖多美多布拉","Sao Tome Dobra"],
"SVC":["薩爾瓦多科朗","Salvadoran Colon"],
"SYP":["敘利亞鎊","Syrian Pound"],
"SZL":["斯威士蘭里蘭吉尼","Swazi Lilangeni"],
"THB":["泰銖","Thai Baht"],
"TJS":["塔吉克斯坦索莫尼","Tajikistan Somoni"],
"TMT":["土庫曼斯坦馬納特","Turkmenistan Manat"],
"TND":["突尼斯第納爾","Tunisian Dinar"],
"TOP":["湯加潘加","Tongan Pa'Anga"],
"TRY":["土耳其里拉","Turkish Lira"],
"TTD":["特立尼達多巴哥元","Trinidad and Tobago Dollar"],
"TWD":["新台幣","New Taiwan Dollar"],
"TZS":["坦桑尼亞先令","Tanzanian Shilling"],
"UAH":["烏克蘭格里夫納","Ukrainian Hryvnia"],
"UGX":["烏干達先令","Ugandan Shilling"],
"USD":["美元","United States Dollar"],
"UYU":["烏拉圭比索","Uruguayan Peso"],
"UZS":["烏茲別克斯坦蘇姆","Uzbekistani Som"],
"VEF":["委內瑞拉玻利瓦爾","Venezuelan Bolivar Fuerte"],
"VND":["越南盾","Viet Nam Dong"],
"VUV":["瓦努阿圖瓦圖","Vanuatu Vatu"],
"WST":["薩摩亞塔拉","Samoa Tala"],
"XAF":["中非法郎","Central African CFA Franc"],
"XAG":["銀價盎司","Ounces of Silver"],
"XAU":["金價盎司","Ounces of Gold"],
"XCD":["東加勒比元","East Caribbean Dollar"],
"XCP":["銅價盎司","Ounces of Copper"],
"XDR":["IMF特別提款權","IMF Special Drawing Rights"],
"XOF":["西非法郎","West African CFA"],
"XPD":["鈀價盎司","Ounces of Palladium"],
"XPF":["太平洋法郎","French Pacific Franc"],
"XPT":["珀價盎司","Ounces of Platinum"],
"YER":["也門里亞爾","Yemeni Rial"],
"ZAR":["南非蘭特","South African Rand"],
"ZMW":["贊比亞克瓦查","Zambian Kwacha"],
"ZWL":["津巴布韋元","Zimbabwean Dollar"]
};

console.dir(CURRENCY.TWD);
